"""add time to appointment

Revision ID: b3f6fabb3100
Revises: 
Create Date: 2025-08-21 11:12:21.444227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3f6fabb3100'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.alter_column('time',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Time(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
